# Generated by Django 6.0.3 on 2026-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("ADMIN", "Admin"),
                    ("SUPERADMIN", "Superadmin"),
                ],
                default="USER",
                max_length=10,
            ),
        ),
    ]
