# Generated by Django 6.0.3 on 2026-03-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("SUPERADMIN", "Superadmin")],
                default="ADMIN",
                max_length=10,
            ),
        ),
    ]
