# Generated by Django 6.0.3 on 2026-03-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_initial"),
        ("products", "0002_alter_product_image_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to="products.product",
            ),
        ),
    ]
